obj:Timestamptest Datetest

Timestamptest:Timestamp.cpp TimestampTest.cpp Timestamp.h Comparable.h
	g++ -o Timestamptest Timestamp.cpp TimestampTest.cpp

Datetest:  Date.cpp Datetest.cpp Date.h Comparable.h
	g++ -o Datetest Date.cpp Datetest.cpp
